'use strict';

export const CONNECTION_CHECKED = 'CONNECTION_CHECKED';
export const CONNECTION_CHECKING = 'CONNECTION_CHECKING';
export const CONNECTION_ONLINE = 'CONNECTION_ONLINE';
export const CONNECTION_OFFLINE = 'CONNECTION_OFFLINE';
export const OFFLINE_ITEMS_LOADED = 'OFFLINE_ITEMS_LOADED';
